name: Python Data Pipeline & ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Cache pip packages for faster runs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run data cleaning & analysis
      - name: Run Coaster Analysis
        run: |
          python coaster_analysis.py

      # 6. Run ML pipeline
      - name: Run Cost Prediction
        run: |
          python mlmodel.py

      # 7. Upload plots as artifacts
      - name: Upload plots
        uses: actions/upload-artifact@v3
        with:
          name: coaster-plots
          path: plots/
