name: Python Data Pipeline & ML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Cache pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Check if raw CSV exists
      - name: Verify data file
        run: |
          if [ ! -f "./data/coaster_db.csv" ]; then
            echo "ERROR: data/coaster_db.csv is missing!"
            exit 1
          fi

      # 6. Run data cleaning
      - name: Run Coaster Analysis
        run: |
          python coaster_analysis.py

      # 7. Check if cleaned CSV exists
      - name: Verify cleaned CSV
        run: |
          if [ ! -f "./data/coaster_db_clean.csv" ]; then
            echo "ERROR: data/coaster_db_clean.csv was not created!"
            exit 1
          fi

      # 8. Run ML pipeline
      - name: Run Cost Prediction
        run: |
          python coaster_cost_prediction.py

      # 9. Upload plots
      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: coaster-plots
          path: plots/

